### ISSUE TITLE
Wadl Import Failed

### ISSUE THREAD

**Issue by LorandLorincz** [jarroda/ServiceStack.Api.Postman#10]
Hi,

Importing the wadl from pentaho bi-platform doesen't work. I tried import from URL, File and Raw Text.

This is the link to the wadl.
http://javadoc.pentaho.com/bi-platform500/webservice500/application.wadl

Thnaks.

**Comment by jarroda** [comment]
I think there may be some misunderstanding of what this project is.  This project is a plugin for [ServiceStack](https://servicestack.net/) to take APIs created in that framework (ServiceStack) and generate [Postman](https://www.getpostman.com/) collections.  This project doesn't import external service descriptions, but rather creates the JSON necessary for importing your ServiceStack service into Postman for testing the service.

**Comment by LorandLorincz** [comment]
My bad, in my search frenzy I didn't notice that I got to ServiceStack. I tought I was still on Postmans Issues page. Sorry for wasting your time. Please close this.

**Comment by jarroda** [comment]
No worries!
