### ISSUE TITLE
aspnetSubPath exception when running an AppHostHttpListenerBase

### ISSUE THREAD

**Issue by wwwlicious** [jarroda/ServiceStack.Api.Postman#7]
When running an AppHostHttpListenerBase as the apphost, the aspnetSubPath is null and the Execute override is never being executed.

This leads to an exception on the [following line](https://github.com/jarroda/ServiceStack.Api.Postman/blob/e53a07a02569d067b23f26a15a71dae6c4532c04/ServiceStack.Api.Postman/PostmanMetadataHandler.cs#L208) which prevents the metadata being generated.

Either defaulting the aspnetSubPath field to empty string instead of null or add null check to CalculateAppUrl method to avoid exception being thrown.

**Comment by jarroda** [comment]
Fixed with pull request #8
