### ISSUE TITLE
Collections can no longer be imported in the new edition of postman

### ISSUE THREAD

**Issue by Jeern** [jarroda/ServiceStack.Api.Postman#9]
The new edition of postman can no longer import collections from Servicestack.Api.Postman. It has been a problem since at least the start of July. Postman says: "Failed to import data: Format not recognized". Apparently Postman has changed the format of collections. I have a hard time finding information about this change though. Since you deployed a new Package 21 days ago, I assume you use some combination of settings that still works ? Or perhaps you use an older version of Postman ?

**Comment by iriiiina** [comment]
I have the same issue - I can't import WADL files from link anymore (same files, that I've successfully imported couple of months ago), it says "Failed to import data: format not recognized". But if I copy content of WADL file into "Paste raw text" section then collection is added.

**Comment by Jeern** [comment]
For me paste raw text does not work either. Same issue. I gather it works for some collections then. I guess its just some small format change. If only one could see a total specification of the format somewhere, then it would probably be easy to make a Pull request to ServiceStack.API.Postman to fix it.

**Comment by Jeern** [comment]
I have examined it a bit more and it turns out that the issue is really simple. The json produced is invalid. Postman must have been more relaxed before. In particular the property names in the json are not surrounded by " - I will send a Pull request as soon as I have the time

Update: Sorry I was wrong. I can also make it work using paste raw text. My problem there was I was copying some json formatted by a browser plugin (that removed the quotes). So the issue is still a mystery, and it only happens with the link as Irina said

**Comment by Jeern** [comment]
Sorry I was wrong. I can also make it work using paste raw text. My problem there was I was copying some json formatted by a browser plugin. So the issue is still a mystery, and it only happens with the link as Irina said

**Comment by Jeern** [comment]
Crazy stuff. While looking into the issue Postman must have updated because the issue has disappeared now. I cannot find Postmans release notes, would have been nice to see if it is correct. Anyway if the issue is still gone tomorrow I will close it.

**Comment by jarroda** [comment]
Is this still an issue?  I have tested with the small sample service I have included in this project and it imports correctly for me in Postman 3.1.6 (the current version).

**Comment by iriiiina** [comment]
Not an issue anymore for me.

**Comment by jarroda** [comment]
Awesome.  I'll close this out.
